services:
  web:
    build: .
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    #expose:
    #  - 8000
    env_file: .env
    # this will override whatever is set in the .env
    environment:
      - DEBUG=True
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME-auctions}
      MYSQL_USER: ${DATABASE_USER-mysqluser}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD-unsecure}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD-unsecure}
    expose:
      - ${DATABASE_PORT-3306}
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    expose:
      - 6379
    volumes:
      - redis_data:/bitnami/redis/data
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD-unsecure}
  
# this server will get overridden in production - see docker-compose.prod.yaml
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_fishauctions.conf:/etc/nginx/nginx_fishauctions.conf:ro
    ports:
      - ${HTTP_PORT-80}:80
    restart: always
    depends_on:
      - web

volumes:
  redis_data:
    driver: local
  mariadb_data:
  static_volume:
  media_volume:
  