services:
  web:
    build: .
    container_name: django
    volumes:
      - .:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME-auctions}
      MYSQL_USER: ${DATABASE_USER-mysqluser}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD-unsecure}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD-unsecure}
    expose:
      - ${DATABASE_PORT-3306}
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    expose:
      - 6379
    volumes:
      - redis_data:/bitnami/redis/data
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD-unsecure}
  
  nginx:
    image: ${NGINX_IMAGE-nginx}:latest # default setting is for development, use lscr.io/linuxserver/swag for production
    volumes:
      # the root conf file is set for dev, but for production use:
      # NGINX_CONF='./nginx.prod.conf'
      # NGINX_CONF_LOCATION='/config/nginx/site-confs/default.conf'
      - ${NGINX_CONF-./nginx.dev.conf}:${NGINX_CONF_LOCATION-/etc/nginx/nginx.conf}
      - ./swag:/config
      - ./nginx_fishauctions.conf:/etc/nginx/nginx_fishauctions.conf:ro
      - static_volume:/home/app/web/staticfiles:ro
      - media_volume:/home/app/web/mediafiles:ro
    ports:
      - ${HTTP_PORT-80}:80
      - ${SSL_PORT-443}:443 # this is only used in production
    restart: always
    depends_on:
      - web
    cap_add:
      - NET_ADMIN
    environment: # none of these get used in development
      - PUID=${PUID-1000}
      - PGID=${PGID-1000}
      - TZ=Etc/UTC
      - URL=${SITE_DOMAIN}
      - VALIDATION=http
      - EMAIL=${ADMIN_EMAIL}

volumes:
  redis_data:
  mariadb_data:
  static_volume:
  media_volume:
  