services:
  web:
    environment:
      - DEBUG: False

  nginx:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID-1000}
      - PGID=${PGID-1000}
      - TZ=Etc/UTC
      - URL=${SITE_DOMAIN}
      - VALIDATION=http
      - EMAIL=${ADMIN_EMAIL}
    volumes:
      - ./swag:/config
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${SSL_PORT-443}:443