services:
  web:
    build: .
    volumes:
      #- .:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME-auctions}
      MYSQL_USER: ${DATABASE_USER-mysqluser}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD-unsecure}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD-unsecure}
    ports:
      - ${DATABASE_PORT-3306}
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD-unsecure}
  
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=${SITE_DOMAIN}
      - VALIDATION=http
      - EMAIL=${ADMIN_EMAIL}
    volumes:
      - ./swag:/config
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ./nginx.conf:/config/nginx/site-confs/default.conf
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    depends_on:
      - web

volumes:
  redis_data:
    driver: local
  mariadb_data:
  static_volume:
  media_volume:
  