line-length = 120
[format]
exclude = ["get-pip.py"]

[lint]
exclude = ["get-pip.py"]
ignore = [
    "E501",
    "E722",
]
extend-select = [
    "A",    # flake8-builtins
    # "ARG",  # flake8-unused-arguments
    # "B",    # flake8-bugbear
    "C4",    # flake8-comprehensions
    # "C90",  # McCabe Complexity
    # "D",    # pydocstyle
    # "DJ",   # flake8-django
    "E",    # pycodestyle
    "EM",   # flake8-errmsg
    # "ERA",  # eradicate
    "DTZ",  # flake8-datetimez
    "F",    # pyflakes
    "FURB", # refurb
    "G",    # flake8-logging-format
    "I",    # isort
    "ICN",  # flake8-import-conventions
    "LOG",  # flake8-logging
    # "N",    # pep8-naming
    # "PL",   # pylint
    "PT",   # flake8-pytest-style
    "PTH",  # flake8-use-pathlib
    # "RET",  # flake8-return
    # "RUF",  # ruff-specific rules
    # "S",    # flake8-bandit
    # "SIM",  # flake8-simplify
    "TID",  # flake8-tidy-imports
    "T20",  # flake8-print
    "UP",   # pyupgrade
    "W",    # pycodestyle warnings
]
