name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DEBUG: True
  SECRET_KEY: abcde
  ALLOWED_HOST_1: localhost
  ALLOWED_HOST_2:
  ALLOWED_HOST_3: 127.0.0.1
  DATABASE_ENGINE: django.db.backends.mysql
  DATABASE_NAME: auctions
  DATABASE_USER: mysqluser
  DATABASE_PASSWORD: 123456
  DATABASE_HOST: 127.0.0.1
  DATABASE_PORT: 3306
  BASE_URL: https://auction.fish
  EMAIL_USE_TLS: True
  EMAIL_HOST: smtp.example.com
  EMAIL_PORT:
  EMAIL_HOST_USER: user@example.com
  EMAIL_HOST_PASSWORD: 123456
  DEFAULT_FROM_EMAIL: Notifications
  TIME_ZONE: America/New_York
  SITE_DOMAIN: auction.fish
  SITE_URL:  https://auction.fish
  GOOGLE_MEASUREMENT_ID: None
  GOOGLE_TAG_ID: None
  GOOGLE_MAPS_API_KEY: abcde
  ADMIN_EMAIL: admin@example.com
  REDIS_PASS:  123456
  GOOGLE_ADSENSE_ID: None
  STATIC_ROOT: /static
  RECAPTCHA_PUBLIC_KEY: abcde
  RECAPTCHA_PRIVATE_KEY: abcde
  GOOGLE_OAUTH_LINK: key123456.apps.googleusercontent.com

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
