name: Docker images build
on:
  push:
  pull_request:
    branches: [master]

jobs:
  image-build:
    name: Test Images Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./.github/scripts/prepare-ci.sh
      - run: docker compose build
