name: Test
on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./.github/scripts/prepare-ci.sh
      - run: docker compose run --rm test --ci
